# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f7647a5fe1950ab80cfd7f63b33194b2d09097b3d7366546f07c5bceb3279dc31551a627af635acdf47e987f5ac03975ea09b564e4b053e13ad305414e692000

test:
  secret_key_base: 6c6a565700f0a6c3acb327dd33a52bb129f8e6149c2660699d6f57a71c8adf1c2b1759a675c401a6c4da6cf382a87711a2307627ca14eb4b01498a0d80b1d25a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
